class ApiPaths:
    HEALTH = "/health"
    AUTH_SIGNUP = "/auth/signup"
    AUTH_LOGIN = "/auth/login"
    SEARCH_ARTICLES = "/search/articles"
    ARTICLES = "/articles"
    ARTICLE_BY_ID = "/articles/{page_id}"
    ARTICLE_TAGS = "/articles/{page_id}/tags"
    WIKI_SEARCH_URL = "https://en.wikipedia.org/w/api.php"
    WIKI_SUMMARY_URL = "https://en.wikipedia.org/api/rest_v1/page/summary"
