class CommonLog:
    SUCCESS = "success"
    SEARCH_REQUEST = "Received search request for keyword: {keyword}"
    SIGNUP_REQUEST = "Received signup request for email: {email}"
    LOGIN_REQUEST = "Received login request for email: {email}"
    SAVE_ARTICLE_REQUEST = "Received save article request for email: {email}"
    GET_SAVED_ARTICLE_REQUEST = "Received get saved article request for email: {email}"
    USER_EXISTS = "User already exists"
    INVALID_CREDENTIALS = "Invalid email or password"
    SIGNUP_SUCCESS = "User created successfully"
    ARTICLE_SAVED_SUCCESSFULLY = "Article saved successfully"
    TAGS_UPDATED_SUCCESSFULLY = "Tags updated successfully"
    INVALID_TOKEN = "Invalid token"
    ACCESS_DENIED = "Access Denied"
    ARTICLE_ALREADY_SAVED = "Article already saved"
    UNEXPECTED_ERROR = "Unexpected Error Occurred: {error}"
    INTERNAL_SERVER_ERROR = "Internal Server Error"
    UNEXPECTED_ERROR_FOR_ENDPOINT = "Unexpected Error Occurred: {method} {path}"
    FAILED_TO_GENERATE_TAGS = "Failed to generate tags with error: {error}"
    AI_GENERATED_TAGS = "AI Generated Tags: {tags}"
    UPDATE_TAG_FAILED = (
        "Update tag failed for user={email} page_id={page_id} error={error}"
    )
